name: StuffBucket
options:
  bundleIdPrefix: com.digitalhandstand
  deploymentTarget:
    iOS: "17.0"
    macOS: "14.0"
  createIntermediateGroups: true
fileGroups:
  - spec.md
  - Implementation_Plan.md
  - AI_Copy.md
  - project.yml

settings:
  base:
    SWIFT_VERSION: 5.9
    DEAD_CODE_STRIPPING: YES
    ENABLE_USER_SCRIPT_SANDBOXING: YES
    STRING_CATALOG_GENERATE_SYMBOLS: YES

schemes:
  StuffBucket:
    build:
      targets:
        StuffBucket: all
    test:
      targets:
        - StuffBucketTests
    run:
      config: Debug
  StuffBucketMac:
    build:
      targets:
        StuffBucketMac: all
    test:
      targets:
        - StuffBucketMacTests
    run:
      config: Debug

targets:
  StuffBucket:
    type: application
    platform: auto
    supportedDestinations: [iOS]
    sources:
      - path: Sources/StuffBucket
      - path: Sources/StuffBucketShared
      - path: Sources/StuffBucketSharedUI
    resources:
      - path: Sources/StuffBucket/Resources
    dependencies:
      - target: StuffBucketCore_iOS
      - target: StuffBucketShareExtension
        embed: true
    settings:
      base:
        INFOPLIST_FILE: Sources/StuffBucket/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.digitalhandstand.stuffbucket
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: V37U525228
        DEAD_CODE_STRIPPING: YES
        SDKROOT: auto
        SUPPORTED_PLATFORMS: "iphoneos iphonesimulator"
        SUPPORTS_MACCATALYST: NO
        SUPPORTS_MAC_DESIGNED_FOR_IPHONE_IPAD: YES
        SUPPORTS_XR_DESIGNED_FOR_IPHONE_IPAD: YES
        CODE_SIGN_ENTITLEMENTS: Sources/StuffBucket/StuffBucket.entitlements

  StuffBucketMac:
    type: application
    platform: auto
    supportedDestinations: [macOS]
    sources:
      - path: Sources/StuffBucketMac
      - path: Sources/StuffBucketShared
      - path: Sources/StuffBucketSharedUI
    resources:
      - path: Sources/StuffBucketMac/Resources
    dependencies:
      - target: StuffBucketCore_macOS
      - target: StuffBucketMacShareExtension
        embed: true
    settings:
      base:
        INFOPLIST_FILE: Sources/StuffBucketMac/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.digitalhandstand.stuffbucket.mac
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: V37U525228
        DEAD_CODE_STRIPPING: YES
        SDKROOT: auto
        SUPPORTED_PLATFORMS: macosx
        SUPPORTS_MACCATALYST: NO
        SUPPORTS_MAC_DESIGNED_FOR_IPHONE_IPAD: NO
        TARGETED_DEVICE_FAMILY: ""
        CODE_SIGN_ENTITLEMENTS: Sources/StuffBucketMac/StuffBucketMac.entitlements

  StuffBucketCore:
    type: framework
    platform: [iOS, macOS]
    sources:
      - path: Sources/StuffBucketCore
    dependencies:
      - sdk: libsqlite3.tbd
    settings:
      base:
        INFOPLIST_FILE: Sources/StuffBucketCore/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.stuffbucket.StuffBucketCore
        DEAD_CODE_STRIPPING: YES
        ENABLE_MODULE_VERIFIER: YES
        MODULE_VERIFIER_SUPPORTED_LANGUAGE_STANDARDS: "gnu11 gnu++14"

  StuffBucketShareExtension:
    type: app-extension
    platform: iOS
    supportedDestinations: [iOS]
    sources:
      - path: Sources/StuffBucketShareExtension
      - path: Sources/StuffBucketShared
    settings:
      base:
        INFOPLIST_FILE: Sources/StuffBucketShareExtension/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.digitalhandstand.stuffbucket.share
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: V37U525228
        CODE_SIGN_ENTITLEMENTS: Sources/StuffBucketShareExtension/StuffBucketShareExtension.entitlements
        APPLICATION_EXTENSION_API_ONLY: YES
    dependencies:
      - sdk: Social.framework

  StuffBucketTests:
    type: bundle.unit-test
    platform: iOS
    supportedDestinations: [iOS]
    sources:
      - path: Tests/StuffBucketTests
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
        PRODUCT_BUNDLE_IDENTIFIER: com.digitalhandstand.stuffbucket.tests
    dependencies:
      - target: StuffBucket

  StuffBucketMacShareExtension:
    type: app-extension
    platform: macOS
    supportedDestinations: [macOS]
    sources:
      - path: Sources/StuffBucketMacShareExtension
      - path: Sources/StuffBucketShared
    settings:
      base:
        INFOPLIST_FILE: Sources/StuffBucketMacShareExtension/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.digitalhandstand.stuffbucket.mac.share
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: V37U525228
        CODE_SIGN_ENTITLEMENTS: Sources/StuffBucketMacShareExtension/StuffBucketMacShareExtension.entitlements
        APPLICATION_EXTENSION_API_ONLY: YES

  StuffBucketMacTests:
    type: bundle.unit-test
    platform: macOS
    supportedDestinations: [macOS]
    sources:
      - path: Tests/StuffBucketMacTests
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
        PRODUCT_BUNDLE_IDENTIFIER: com.digitalhandstand.stuffbucket.mactests
        TEST_HOST: $(BUILT_PRODUCTS_DIR)/StuffBucketMac.app/Contents/MacOS/StuffBucketMac
        BUNDLE_LOADER: $(TEST_HOST)
    dependencies:
      - target: StuffBucketMac
