name: StuffBucket
options:
  bundleIdPrefix: com.stuffbucket
  deploymentTarget:
    iOS: "17.0"
    macOS: "14.0"
  createIntermediateGroups: true
fileGroups:
  - spec.md
  - Implementation_Plan.md
  - AI_Copy.md
  - project.yml

settings:
  base:
    SWIFT_VERSION: 5.9

targets:
  StuffBucket:
    type: application
    platform: iOS
    sources:
      - path: Sources/StuffBucket
    resources:
      - path: Sources/StuffBucket/Resources
    dependencies:
      - target: StuffBucketCore_iOS
    settings:
      base:
        INFOPLIST_FILE: Sources/StuffBucket/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.stuffbucket.StuffBucket
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon

  StuffBucketMac:
    type: application
    platform: macOS
    sources:
      - path: Sources/StuffBucketMac
    resources:
      - path: Sources/StuffBucketMac/Resources
    dependencies:
      - target: StuffBucketCore_macOS
    settings:
      base:
        INFOPLIST_FILE: Sources/StuffBucketMac/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.stuffbucket.StuffBucketMac
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon

  StuffBucketCore:
    type: framework
    platform: [iOS, macOS]
    sources:
      - path: Sources/StuffBucketCore
    settings:
      base:
        INFOPLIST_FILE: Sources/StuffBucketCore/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.stuffbucket.StuffBucketCore
